name: fiemap
version: git
version-script: |
    echo $(git describe --tags)
summary: file extent dumping tool
description: fiemap dumps the extents of files allowing one to see how much fragmentation is in a file

confinement: strict

parts:
    fiemap:
        plugin: make
        source: git://github.com/ColinIanKing/fiemap
        build-packages:
            - gcc
            - make
apps:
    fiemap:
        command: usr/bin/fiemap
        plugs: [home]

